stages:
    - Golangci-lint
    - UnitTest
    - BuildTest

Golangci-lint:
  image: golangci/golangci-lint:v1.47.3-alpine
  tags:
    - golang-ci-lint
  stage: Golangci-lint
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    paths:
      - .go/pkg/mod/
  before_script:
      - mkdir -p /go/src/live_go
      - cp -r . /go/src/live_go
      - cd /go/src/live_go
      - go get ./...
  script:
    - golangci-lint run ./... --timeout=5m

UnitTest:
  image: tetafro/golang-gcc:1.17-alpine
  tags:
    - golang-acc
  stage: UnitTest
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    paths:
      - .go/pkg/mod/
  before_script:
    - mkdir -p /go/src/live_go
    - cp -r . /go/src/live_go
    - cd /go/src/live_go
  script:
    - go test `go list ./...`

BuildTest:
  image: tetafro/golang-gcc:1.17-alpine
  tags:
    - golang-acc
  stage: BuildTest
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    paths:
      - .go/pkg/mod/
  before_script:
    - mkdir -p /go/src/live_go
    - cp -r . /go/src/live_go
    - cd /go/src/live_go
  script:
    - go build
