mysql:
  idleConns: 10
  openConns: 100
  AccountDB:
    debug: false
    master:
      host: wenflow_mysql
      port: 3306
      user: root
      password: Qwer1234
    slave:
      host: wenflow_mysql
      port: 3306
      user: root
      password: Qwer1234
  ProductDB:
    debug: false
    master:
      host: wenflow_mysql
      port: 3306
      user: root
      password: Qwer1234
    slave:
      host: wenflow_mysql
      port: 3306
      user: root
      password: Qwer1234
