redis:
  maxIdle: 10
  maxActive: 100
  Central:
    master:
      host: wenflow_redis
      port: 6379
      password: q96ej3z04
      index: 1
    slave:
      host: wenflow_redis
      port: 6379
      password: q96ej3z04
      index: 1
  Member:
    master:
      host: wenflow_redis
      port: 6379
      password: q96ej3z04
      index: 2
    slave:
      host: wenflow_redis
      port: 6379
      password: q96ej3z04
      index: 2
